- name: INSTALLING PACKAGES
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing packages in order
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - mysql
    - git
    - zip
    - httpd
