- name: BABAI HOTEL
  hosts: local
  connection: local
  vars:
    hotel_name: The babai hotel - Telugu spices
    capacity: 1000
    location: Hyderabad
    specialities:
    - Ragi Mudha
    - Chicken Pickles
    - Gobi manchurian
    - Avakai rasam
    open: true
    chefs:
      headchef: "saikumar"
      juniorchef: "Balu"
  tasks:
  - name: Printing hotel information
    ansible.builtin.debug:
      msg: "Presenting {{ hotel_name }} with people capacity of {{ capacity }} situated in {{ location }} and its famous for {{ specialities }} is it {{ open }} : yes and there chefs are {{ headchef }} and his assistant is {{ juniorchef }}"