- name: INSTALLATION OF NGINX
  hosts: web
  become: yes
  tasks:
  - name: installing nginx package
    ansible.builtin.package:
      name: ntpdate
      state: present
  - name: starting the nginx services
    ansible.builtin.service:
      name: httpd
      state: started