- name: VARIABLES CONCEPT
  hosts: local
  connection: local
  vars:
    MILLION: "million"
    POWER: is power
    GOD: always towards god
  tasks:
  - name: printing the variables names
    ansible.builtin.debug:
      msg: "Saikumar has {{ MILLION }} , Knowledge {{ POWER }} , Willpower {{ GOD }}"