- name: VARIABLES CONCEPT
  hosts: local
  connections: local
  tasks:
    name: printing the variables names
    ansible.builtin.debug:
      msg: "Saikumar has million , Knowledge is Power , Willpower always towards God"